name = "gak-cms-backend"
main = "dist/index.js"  # Point to the compiled output
outDir = "./dist"        
compatibility_date = "2024-03-05"

[build]
command = "bun install && bunx prisma generate && bun build ./src/index.ts --target=bun"

[build.upload]
format = "service-worker"
