name = "gak-cms-backend"
main = "dist/index.js"
compatibility_date = "2024-03-05"


[build]
command = "rm -f bun.lockb && bun install && bunx prisma generate && bun build ./src/index.ts --target=browser --format=esm --outdir dist"

[build.upload]
format = "service-worker"