name = "gak-cms-backend"
main = "src/index.ts"
compatibility_date = "2024-03-05"

[build]
command = "bun install && bunx prisma generate --no-engine && bun build ./src/index.ts --target=bun"

[build.upload]
format = "service-worker"