name = "gak-cms-backend"
main = "dist/index.js"
compatibility_date = "2024-03-05"

[vars]
DATABASE_URL = { type = "secret" }

[build]
command = "bun install && bunx prisma generate && bun build ./src/index.ts --target=browser --format=esm --outdir dist"

[build.upload]
format = "service-worker"